#!/bin/bash
cd $HOME

if [[ -n "$1" ]]; then
    desktopName="$1"
    #printf "\nStarting desktop: ${desktopName}\n"

    cd ~
    rm -rf .xinitrc
    touch .xinitrc

    # uncomment the following 2 xrandr if you are using dual monitors
    # may be required if you want to extend your desktop otherwise 
    # the second monitor might just be mirrored
    # run the command below from a terminal to discover what the port names are
    # command: xrandr
    
    # echo "xrandr --output HDMI-1 --primary --auto --output HDMI-3 --auto --right-of HDMI-1" > .xinitrc
    # echo "xrandr --output HDMI-3 --auto --left-of HDMI-1" >> .xinitrc

    case "$desktopName" in
        kali)
            printf "\n*** Starting default desktop kali\n"
            echo "exec xfce4" >> .xinitrc
            ;;
        lxqt)
            printf "\n*** Starting desktop dwm\n"
            echo "exec startlxqt" >> .xinitrc
            ;;
        dwm)
            printf "\n*** Starting desktop dwm\n"
            #echo "dwmblocks &" >> .xinitrc
            echo "slstatus &" >> .xinitrc
            echo "exec dwm" >> .xinitrc
            ;;
    esac
else
    printf "\nNo desktop specified, starting with default desktop."
fi

startx
